### ISSUE TITLE
Unbekannte Option "loadshadowlibrary" vom Paket "todonotes"

### ISSUE THREAD

**Issue by ShineGlurak** [systemtechniklabor/htwsaar-i-mst-vorlage#6]
Beim Erstellen des PDF-Dokuments kommt die Warnung:
"Unknown option `loadshadowlibrary` for package `todonotes`."

Zum Erhalten des Fehlers:
1. Projekt runterladen
2. Das Dokument bauen lassen

**Genutzte Latex-Software**
- TexLive 2019

**Comment by amiede** [comment]
Wurde in 7933a3a gefixt. (Laut Anleitung des Pakets Stand 06/2021 gibt es die Option aber anscheinend noch.)
